#!/bin/bash

julia -e 'using Pkg; Pkg.add("PackageCompiler")'
julia -e 'using PackageCompiler; PackageCompiler.create_sysimage([:Plots, :Perfusion, :MAT]; precompile_execution_file="showDRO.jl", replace_default=true)'

